[package]
name = "tauri-plugin-campus-network-bind"
version = "0.1.0"
description = "把 CampusLogin 安卓进程网络绑定到 WLAN(bindProcessToNetwork)"
edition = "2021"
links = "tauri-plugin-campus-network-bind"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }

[dependencies]
serde = "1"
serde_json = "1"
tauri = { version = "2" }
